# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file initial/pom.xml
    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        unset DOCKER_USER
        unset DOCKER_PASSWORD
    - name: Build Docker image
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        docker build -t "$DOCKER_USER/hello-world:$GITHUB_SHA" ./initial
        unset DOCKER_USER
    - name: Docker push
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        docker push "$DOCKER_USER/hello-world:$GITHUB_SHA"
        unset DOCKER_USER
        docker logout
    - name: Adding config file
      env: 
        KUBERNETES_SECRET: ${{ secrets.KUBERNETES_SECRET }}
      run: |
        echo -e "$KUBERNETES_SECRET" > conf
        unset KUBERNETES_SECRET
    - name: Setting path
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        export KUBECONFIG="$(pwd)/conf"
        kubectl get all -n "$DOCKER_USER"
        unset DOCKER_USER
    - name: Updateing deployment
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        kubectl set image deployment/new api="$DOCKER_USER/hello-world:$GITHUB_SHA" -n "$DOCKER_USER" --record
        unset DOCKER_USER
    - name: Removing conf
      run: |
        rm -rf conf
        unset KUBECONFIG
